In [23]:
import pandas as pd

df = pd.read_csv('data.csv', keep_default_na=False, na_values=[''])
df

,name,yearEstablished,state,stateAbbreviation,locationType,locationTypeKind,typeOwned,typeProfit,level,hasUndergraduate,...,closedByRegion_2024,totalByState_2025,closedByState_2025,totalByRegion_2025,closedByRegion_2025,regionUnemploymentRate,totalByStateMean,totalByRegionMean,closedByStateMean,closedByRegionMean
0,Alderson Broaddus University,1871,West Virginia,WV,Rural,Distant,Private,Nonprofit,4-year,True,...,4,69,0,2055,2,3.6,69.0,2054.75,0.50,1.50
1,Alliance University (Formerly Nyack College),1882,New York,NY,City,Large,Private,Nonprofit,4-year,True,...,8,413,0,1163,0,4.1,413.0,1163.00,1.00,2.25
2,Ancilla College,1937,Indiana,IN,Rural,Distant,Private,Nonprofit,2-year,True,...,9,102,0,1323,4,4.1,102.0,1322.25,0.25,3.25
3,Becker College,1784,Massachusetts,MA,City,Midsize,Private,Nonprofit,4-year,True,...,8,144,0,1163,0,4.1,144.0,1163.00,0.50,2.25
4,Bloomfield College,1868,New Jersey,NJ,Suburb,Large,Private,Nonprofit,4-year,True,...,8,144,0,1163,0,4.1,144.0,1163.00,0.25,2.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Eastern Nazarene College,1900,Massachusetts,MA,Suburb,Large,Private,Nonprofit,4-year,True,...,8,144,0,1163,0,4.1,144.0,1163.00,0.50,2.25
61,Cox College,1907,Missouri,MO,City,Midsize,Private,Nonprofit,4-year,True,...,9,137,2,1323,4,4.1,136.5,1322.25,0.25,3.25
62,University of Wisconsin–Platteville Richland,1967,Wisconsin,WI,Town,Distant,Public,Nonprofit,4-year,True,...,9,88,1,1323,4,4.1,88.0,1322.25,0.50,3.25
63,Maryland University of Integrative Health,1974,Maryland,MD,Suburb,Large,Private,Nonprofit,graduate school,False,...,4,77,1,2055,2,3.6,77.0,2054.75,0.00,1.50
64,B. H. Carroll Theological Seminary,2004,Texas,TX,City,Midsize,Private,Nonprofit,seminary,False,...,4,384,1,2055,2,3.6,384.0,2054.75,0.00,1.50

In [24]:
totals = ['totalByState_2020', 'totalByState_2021', 'totalByState_2022',
                       'totalByState_2023', 'totalByState_2024', 'totalByState_2025']
n_s_temp = df.groupby('state')[totals].mean()
n_s = n_s_temp.mean(axis=1).round(0)
y_s = df['state'].value_counts()
all_states = pd.Index(list(n_s.index) + list(y_s.index)).unique()
n_s = n_s.reindex(all_states)
y_s = y_s.reindex(all_states)

a = 2
b = 2

a_post = a + y_s
b_post = b + n_s - y_s

post_means = a_post / (a_post + b_post)
post_vars = (a_post * b_post) / ((a_post + b_post)**2 * (a_post + b_post + 1))

results = pd.DataFrame({
    'n_s': n_s,
    'y_s': y_s,
    'a_post': a_post,
    'b_post': b_post,
    'post_mean': post_means,
    'post_var': post_vars
})

results = results.reset_index().rename(columns={'index': 'state'})
results

            state    n_s  y_s  a_post  b_post  post_mean  post_var
0         Alabama   78.0    2       4    78.0   0.048780  0.000559
1      California  657.0    6       8   653.0   0.012103  0.000018
2        Delaware   16.0    1       3    17.0   0.150000  0.006071
3         Florida  320.0    2       4   320.0   0.012346  0.000038
4        Illinois  236.0    5       7   233.0   0.029167  0.000117
5         Indiana  102.0    2       4   102.0   0.037736  0.000339
6            Iowa   75.0    1       3    76.0   0.037975  0.000457
7        Maryland   77.0    1       3    78.0   0.037037  0.000435
8   Massachusetts  144.0    3       5   143.0   0.033784  0.000219
9        Michigan  154.0    2       4   154.0   0.025316  0.000155
10       Missouri  137.0    3       5   136.0   0.035461  0.000241
11       Nebraska   40.0    1       3    41.0   0.068182  0.001412
12         Nevada   35.0    1       3    36.0   0.076923  0.001775
13  New Hampshire   34.0    1       3    35.0   0.078947  0.001864
14     New Jersey  144.0    1       3   145.0   0.020270  0.000133
15       New York  413.0    7       9   408.0   0.021583  0.000051
16           Ohio  274.0    4       6   272.0   0.021583  0.000076
17       Oklahoma   93.0    1       3    94.0   0.030928  0.000306
18         Oregon   73.0    2       4    73.0   0.051948  0.000631
19   Pennsylvania  289.0    4       6   287.0   0.020478  0.000068
20   South Dakota   28.0    1       3    29.0   0.093750  0.002575
21      Tennessee  146.0    1       3   147.0   0.020000  0.000130
22          Texas  384.0    1       3   385.0   0.007732  0.000020
23           Utah   58.0    1       3    59.0   0.048387  0.000731
24        Vermont   19.0    1       3    20.0   0.130435  0.004726
25       Virginia  138.0    1       3   139.0   0.021127  0.000145
26  West Virginia   69.0    2       4    69.0   0.054795  0.000700
27      Wisconsin   88.0    7       9    83.0   0.097826  0.000949

In [25]:
results['y_s'].sum()

65